### ISSUE TITLE
Asset ID - Does not escape "/" character

### ISSUE THREAD

**Issue by redgouf** [rodriada000/SessionMapSwitcher#10]
When creating a Catalog, you are able to add a "/" to the "Asset ID" field, and no error/warning is thrown. When trying to download/install that specific file after the Catalog is loaded, the item will fail to install.

Once you remove the "/" from the Asset ID name, the file will install correctly.

**Comment by rodriada000** [comment]
fixed in rodriada000/SessionModManagerCore@775fd75d69cbd80c4b19e69feae5b6c1ea1def90

awaiting next release.
