### ISSUE TITLE
Asset ID - automatically append '.zip'

### ISSUE THREAD

**Issue by redgouf** [rodriada000/SessionMapSwitcher#11]
Can it be possible to automatically append the ',zip' to the Asset ID field? It is not fun to manually add ".zip / .rar" to that field.

**Comment by rodriada000** [comment]
Changes made in  rodriada000/SessionModManagerCore@c4eb628e17460460b7ea92ae76e5c554d088a0e2 and 0b1f0fcf567332d2328020139764c729c173ef3e

There is now a dropdown to select '.zip' or '.rar' (defaults to '.zip') and you don't have to manually add '.zip / .rar' to the Asset ID field.

awaiting next release.
