### ISSUE TITLE
Thumbnails - Fetch new Thumbnail / Replace

### ISSUE THREAD

**Issue by redgouf** [rodriada000/SessionMapSwitcher#12]
When updating and changing the Thumbnail image on an Asset, the thumbnail is not actually updated on the SMM fetch.

This only seems to happen when the user has already previewed that item and downloaded the original Thumbnail.

**Comment by rodriada000** [comment]
fixed in rodriada000/SessionModManagerCore@775fd75d69cbd80c4b19e69feae5b6c1ea1def90

awaiting next release.
