### ISSUE TITLE
Says Patch with illusory mod unlocker, and doesn't work

### ISSUE THREAD

**Issue by ghost** [rodriada000/SessionMapSwitcher#15]
In the readme it says it should be patched with ezpz, my SMM doesnt say that it says patch with illusory Mod unlocker, I open it, point it at the game dir, and doesn't work. Have tried somehow doing admin priv, everything and nope not working. Any tips?

**Comment by ghost** [comment]
Managed to get it working but having fatal errors and cant load

**Comment by rodriada000** [comment]
The readme is out of date as of v2.6.0

Older mods are not compatible with the latest Session update (0.0.0.5). The modders must re-cook their mods with UE 4.24

Make sure you have no old mods installed if it's crashing

**Comment by ghost** [comment]
the only thing i am trying which is the tampa map, which is the newest map updated, and im getting serialization error corrupt data found, please verify your installation.
Is there no maps updated for 0.0.5?

**Comment by rodriada000** [comment]
As of this time there are no maps working with 0.0.0.5.

The modding folks are working on it trying to figure it out. Should take a day or two, they are pretty quick

**Comment by ghost** [comment]
ah ok perfect so! Just making sure everything is working on my end is all! Thanks for the updates, and the amazing work !

**Comment by rodriada000** [comment]
updated README to reflect v2.6.X changes.
