### ISSUE TITLE
Illusory Mod unlocker doesn't work?

### ISSUE THREAD

**Issue by ZodiacInsanity** [rodriada000/SessionMapSwitcher#16]
I downloaded the latest update, and i tried to patch using the illusory mod unlocker, its directed to the session folder and says it patched the game but the Mod manager says i haven't patched it yet.

**Comment by rodriada000** [comment]
Set the path in the illusory mod unlocker to be `Session/SessionGame/Binaries/Win64` 

It sounds like you didn't set the path correctly so try the above.

**Comment by ZodiacInsanity** [comment]
Thanks man! That fixed it
