### ISSUE TITLE
R: Open Installed Mods Folder

### ISSUE THREAD

**Issue by luminsnce** [rodriada000/SessionMapSwitcher#23]
Hey,

I was wondering whether we could get a button thats opening the mod folder to quickly uninstall or change some mods. Since the mod folder is already read by SMM I thought it wouldn't be a hard change.

Thanks :)

**Comment by rodriada000** [comment]
If you right-click the list of maps there are options to open the Session folder, Content folder, or map folder. So that feature is already there pretty much
