### ISSUE TITLE
Session Mod Manager wont open

### ISSUE THREAD

**Issue by varobw** [rodriada000/SessionMapSwitcher#25]
Hi! I recently used Session Mod Manager, i Installed RMS Toolkit as well as some mods that seem to be working right now. The thing is, i cant open Session Mod Manager, it doesn't give an error or anything, the mouse icon shows the loading wheel for a second before it dissapears, and nothing happens. Any clues? I dont get what happened.

Thanks!

**Comment by rodriada000** [comment]
please attach the "applog.txt" file with the error. otherwise closing issue.
