### ISSUE TITLE
looking to collaborate regarding sparow mods

### ISSUE THREAD

**Issue by ghost** [rodriada000/SessionMapSwitcher#26]
hi there, 

I am reaching out regarding sparow's mods and maps. Thhey seem to always be broken on the mod manager, and Ive been working close with him to fix that. 

I have an updated list of google drive links, or I planned on building a stand alone mod manager. I would prefer the former as your team has the framework in place. 

I have mod manager's I've made in my repository for the VR community. if your team just needs the updxated links, great, if its a dev issue, let me know and Im happy to help. Thanks. 

Sorry if this isnt the best way to connect, I tried contacting the illustrious discord.

**Comment by rodriada000** [comment]
Hi - I'm guessing Sparow is a person/modder? If they are making mods for Session, then Session Mod Manager (SMM) should work no problem with them.

What exactly is "broken" on the map/mods? 

Do the updated Google drive links you have work with SMM?

**Comment by ghost** [comment]
yes he builds (my opinion) some of the most expansive maps. RIght now all his links on the mod mang are broken. the proper links I built a google doc for. his name is spargo808*

   https://docs.google.com/spreadsheets/d/1x7fWhrwYsrNFaKM0mqQXfJ-FtQyT-w6GvJX2zvZNsk4/edit#gid=1268018012

**Comment by rodriada000** [comment]
Thanks for the updated links. I've updated the SMM asset store catalog with the new links. Should be all set.
