### ISSUE TITLE
"Start Session" using a launch option

### ISSUE THREAD

**Issue by AlmisuiFR** [rodriada000/SessionMapSwitcher#28]
Hi! On launch, got the following message:
_"DX12 is not supported on your system. Try running without the -dx12 or -d3d12 command line argument"_

On Steam, I use a launch option ( _-d3d12_ ) to run the game, which is accessible from the parameters.
But I didn't find a way to "Start Session" using SessionModManager.

Any solution?
Thanks!

EDIT: loading from SMM then launching the game from Steam is working fine: we have to return to apartment and load "brooklyn banks" to be redirected to the imported map :)

**Comment by rodriada000** [comment]
If this is still an issue I can add an option to set command line arguments in the settings page of SMM.

**Comment by rodriada000** [comment]
this has been added in v3.0.5 https://github.com/rodriada000/SessionMapSwitcher/releases/tag/v3.0.5
