### ISSUE TITLE
Preview images do not load

### ISSUE THREAD

**Issue by smokeanthrax** [rodriada000/SessionMapSwitcher#30]
Hey there! Just a simple issue that doesn't need much explaining. In the Asset Store, preview images do not load. Ever.

A couple images loaded when I first got this program a few weeks ago, but never again after that. Every asset's just stuck on "loading preview image ... "

I'm on the latest version.

Thanks in advance!

**Comment by luiza177** [comment]
I'm having the same issue.

**Comment by rodriada000** [comment]
This is an issue with the discord URLs being invalid in the catalog. I'm re-scraping the catalog to get the new URLs. should be fixed in the next day or so.
