### ISSUE TITLE
Crashing whenever the two lower side buttons are clicked.

### ISSUE THREAD

**Issue by luiza177** [rodriada000/SessionMapSwitcher#31]
Just as the title says, happens every single time. 

<img width="674" alt="Screenshot 2024-07-05 122420" src="https://github.com/rodriada000/SessionMapSwitcher/assets/40475976/ff3f7bbd-b59f-4f22-b847-9473f8588840">

I'm on Windows 11, downloaded the latest version. Might try building from source.

**Comment by luiza177** [comment]
Clicking the text box in the asset store to search also causes it to crash.

I'm also unable to build from source because ModManagerUnitTests and SessionModManagerCore are missing.

**Comment by rodriada000** [comment]
@luiza177 could you please post the "applog.txt" so I can see if there is an error logged. I'm working on some updates for the app now.

**Comment by luiza177** [comment]
I ended up doing a clean Windows reinstall, because I noticed similar problems in other places. That did the trick, something in Windows was probably corrupted.
